# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Ensure snapd is installed and running
  ansible.builtin.include_role:
    name: jcook3701.utils.snap

- name: Install Visual Studio Htop via Snap
  community.general.snap:
    name: htop
    classic: true
    state: "{{ htop_state | default('present') }}"
